<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>scopeName</key>
		<string>text.log</string>

		<key>fileTypes</key>
		<array>
			<string>log</string>
		</array>

		<key>name</key>
		<string>Log file</string>

		<key>patterns</key>
		<array>

			<!-- Log levels -->

			<!-- Trace/Verbose -->
			<dict>
				<key>match</key>
				<string>\b(Trace)\b:</string>

				<key>name</key>
				<string>comment log.verbose</string>
			</dict>

			<!-- Serilog VERBOSE -->
			<dict>
				<key>match</key>
				<string>(?i)\[(verbose|verb|vrb|vb|v)\]</string>

				<key>name</key>
				<string>comment log.verbose</string>
			</dict>

			<!-- Android logcat Verbose -->
			<dict>
				<key>match</key>
				<string>(?<=^[\s\d\p]*)\bV\b</string>

				<key>name</key>
				<string>comment log.verbose</string>
			</dict>

			<!-- DEBUG -->
			<dict>
				<key>match</key>
				<string>\b(DEBUG|Debug)\b|(?i)\b(debug)\:</string>

				<key>name</key>
				<string>markup.changed log.debug</string>
			</dict>

			<!-- Serilog DEBUG -->
			<dict>
				<key>match</key>
				<string>(?i)\[(debug|dbug|dbg|de|d)\]</string>

				<key>name</key>
				<string>markup.changed log.debug</string>
			</dict>

			<!-- Android logcat Debug -->
			<dict>
				<key>match</key>
				<string>(?<=^[\s\d\p]*)\bD\b</string>

				<key>name</key>
				<string>markup.changed log.debug</string>
			</dict>

			<!-- INFO -->
			<dict>
				<key>match</key>
				<string>\b(HINT|INFO|INFORMATION|Info|NOTICE|II)\b|(?i)\b(info|information)\:</string>

				<key>name</key>
				<string>markup.inserted log.info</string>
			</dict>

			<!-- Serilog INFO -->
			<dict>
				<key>match</key>
				<string>(?i)\[(information|info|inf|in|i)\]</string>

				<key>name</key>
				<string>markup.inserted log.info</string>
			</dict>

			<!-- Android logcat Info -->
			<dict>
				<key>match</key>
				<string>(?<=^[\s\d\p]*)\bI\b</string>

				<key>name</key>
				<string>markup.inserted log.info</string>
			</dict>

			<!-- WARN -->
			<dict>
				<key>match</key>
				<string>\b(WARNING|WARN|Warn|WW)\b|(?i)\b(warning)\:</string>

				<key>name</key>
				<string>markup.deleted log.warning</string>
			</dict>

			<!-- Serilog WARN -->
			<dict>
				<key>match</key>
				<string>(?i)\[(warning|warn|wrn|wn|w)\]</string>

				<key>name</key>
				<string>markup.deleted log.warning</string>
			</dict>

			<!-- Android logcat Warning -->
			<dict>
				<key>match</key>
				<string>(?<=^[\s\d\p]*)\bW\b</string>

				<key>name</key>
				<string>markup.deleted log.warning</string>
			</dict>

			<!-- ERROR -->
			<dict>
				<key>match</key>
				<string>\b(ALERT|CRITICAL|EMERGENCY|ERROR|FAILURE|FAIL|Fatal|FATAL|Error|EE)\b|(?i)\b(error)\:</string>

				<key>name</key>
				<string>string.regexp, strong log.error</string>
			</dict>

			<!-- Serilog ERROR -->
			<dict>
				<key>match</key>
				<string>(?i)\[(error|eror|err|er|e|fatal|fatl|ftl|fa|f)\]</string>

				<key>name</key>
				<string>string.regexp, strong log.error</string>
			</dict>

			<!-- Android logcat Error -->
			<dict>
				<key>match</key>
				<string>(?<=^[\s\d\p]*)\bE\b</string>

				<key>name</key>
				<string>string.regexp, strong log.error</string>
			</dict>

			<!-- ISO dates ("2016-08-23") -->
			<dict>
				<key>match</key>
				<string>\b\d{4}-\d{2}-\d{2}(T|\b)</string>

				<key>name</key>
				<string>comment log.date</string>
			</dict>

			<!-- Culture specific dates ("23/08/2016", "23.08.2016") -->
			<dict>
				<key>match</key>
				<string>(?<=(^|\s))\d{2}[^\w\s]\d{2}[^\w\s]\d{4}\b</string>

				<key>name</key>
				<string>comment log.date</string>
			</dict>

			<!-- Clock times with optional timezone ("09:13:16", "09:13:16.323", "09:13:16+01:00") -->
			<dict>
				<key>match</key>
				<string>\d{1,2}:\d{2}(:\d{2}([.,]\d{1,})?)?(Z| ?[+-]\d{1,2}:\d{2})?\b</string>

				<key>name</key>
				<string>comment log.date</string>
			</dict>

			<!-- Git commit hashes of length 40, 10 or 7 -->
			<dict>
				<key>match</key>
				<string>\b([0-9a-fA-F]{40}|[0-9a-fA-F]{10}|[0-9a-fA-F]{7})\b</string>

				<key>name</key>
				<string>constant.language</string>
			</dict>

			<!-- Guids -->
			<dict>
				<key>match</key>
				<string>\b[0-9a-fA-F]{8}[-]?([0-9a-fA-F]{4}[-]?){3}[0-9a-fA-F]{12}\b</string>

				<key>name</key>
				<string>constant.language log.constant</string>
			</dict>

			<!-- MAC addresses: 89:A1:23:45:AB:C0, fde8:e767:269c:0:9425:3477:7c8f:7f1a -->
			<dict>
				<key>match</key>
				<string>\b([0-9a-fA-F]{2,}[:-])+[0-9a-fA-F]{2,}+\b</string>

				<key>name</key>
				<string>constant.language log.constant</string>
			</dict>

			<!-- Constants -->
			<dict>
				<key>match</key>
				<string>\b([0-9]+|true|false|null)\b</string>

				<key>name</key>
				<string>constant.language log.constant</string>
			</dict>

			<!-- String constants -->
			<dict>
				<key>match</key>
				<string>"[^"]*"</string>

				<key>name</key>
				<string>string log.string</string>
			</dict>

			<dict>
				<key>match</key>
				<string>(?<![\w])'[^']*'</string>

				<key>name</key>
				<string>string log.string</string>
			</dict>

			<!-- Exception type names -->
			<dict>
				<key>match</key>
				<string>\b([a-zA-Z.]*Exception)\b</string>

				<key>name</key>
				<string>string.regexp, emphasis log.exceptiontype</string>
			</dict>

			<!-- Colorize rows of exception call stacks -->
			<dict>
				<key>begin</key>
				<string>^[\t ]*at</string>

				<key>end</key>
				<string>$</string>

				<key>name</key>
				<string>string.key, emphasis log.exception</string>
			</dict>

			<!-- Match Urls -->
			<dict>
				<key>match</key>
				<string>\b[a-z]+://\S+\b/?</string>

				<key>name</key>
				<string>constant.language log.constant</string>
			</dict>

			<!-- Match character and . sequences (such as namespaces)
			as well as file names and extensions (e.g. bar.txt) -->
			<dict>
				<key>match</key>
				<string>(?<![\w/\\])([\w-]+\.)+([\w-])+(?![\w/\\])</string>

				<key>name</key>
				<string>constant.language log.constant</string>
			</dict>
		</array>

		<key>uuid</key>
		<string>E81BB6AB-CAC7-4C27-9A79-4137A4693EBD</string>
	</dict>
</plist>
